### ISSUE TITLE
Bower dependency not added

### ISSUE THREAD

**Issue by herzzanu** [kpfefferle/ember-octicons#22]
ember v2.10
ember-cli v2.10.0

**Comment by kpfefferle** [comment]
Thanks for calling this to my attention @herzzanu!

It looks like I forgot to rename the `blueprints/ember-cli-octicons` directory to `blueprints/ember-octicons` when I changed the name of the addon. This has been fixed by commit https://github.com/kpfefferle/ember-octicons/commit/0aebad042b919c2f2a1f64cdf3a39141b8dd1d50 and released on NPM as [v0.7.1](https://github.com/kpfefferle/ember-octicons/releases/tag/v0.7.1)

I tested it myself on a new project, but if you are able to confirm as well, that would be great.

**Comment by herzzanu** [comment]
Thanks @kpfefferle I can confirm it's working now.
